spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat_db
    username: postgres
    password: password2

  flyway:
    url: jdbc:postgresql://localhost:5432/chat_db
    user: postgres
    password: password2
    enabled: true
    locations:
      - 'classpath:db/migration'